_BASE_: "Base-RetinaNet.yaml"
INPUT:
  MIN_SIZE_TRAIN: (800,)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "output_1x"