_BASE_: "Base-RCNN-FPN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (800,)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "output_1x"
